# Makefile_PPC for PPC

MPP_PATH := /opt/hisi-linux-nptl/arm-hisiv100-linux/target/bin

CC = $(MPP_PATH)/arm-hisiv100nptl-linux-gcc
AR = $(MPP_PATH)/arm-hisiv100nptl-linux-ar
TP = $(MPP_PATH)/arm-hisiv100nptl-linuxstrip

LIBS = -lpthread

CFLAGS  = -DHI_DEBUG -g

RM = rm -f

TARGET  = ./cpu

OBJS =  cpu.o

${TARGET}:${OBJS}
	${CC} ${CFLAGS} -o cpu  ${OBJS} ${LIBS}

		cp ./cpu  /hh5500/. -f

		${RM} *.o
